In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import cv2

In [2]:
cams_info_data = scipy.io.loadmat('office/cams_info_no_extr.mat')
kp_data = scipy.io.loadmat('office/kp.mat')
wrld_data = scipy.io.loadmat('office/wrld_info.mat')

In [41]:
print(cams_info_data.keys())
print(cams_info_data['cams_info'][1][0]['focal_lenght'][0,0][0,0])
print(cams_info_data['cams_info'][2][0]['focal_lenght'][0,0][0,0])
print(cams_info_data['cams_info'][3][0]['focal_lenght'][0,0][0,0])
print(cams_info_data['cams_info'][9][0]['rgb'][0][0].shape)
print(cams_info_data['cams_info'][0][0]['depth'][0][0].shape)
print(cams_info_data['cams_info'][0][0]['conf'][0][0].shape)

dict_keys(['__header__', '__version__', '__globals__', 'cams_info'])
409.66916
403.96414
415.427
(512, 256, 3)
(512, 256)
(512, 256)


In [26]:
# print(cams_info_data['cams_info'][9][0])

In [4]:
print(kp_data.keys())
print(kp_data['Feature_img10_00000'][0][0][0])
print(kp_data['Feature_img10_00000'][0][0][1])

print(kp_data['Feature_img1_00000'][0][0][0].shape)
print(kp_data['Feature_img1_00000'][0][0][1].shape)

dict_keys(['__header__', '__version__', '__globals__', 'Feature_img10_00000', 'Feature_img1_00000', 'Feature_img2_00000', 'Feature_img3_00000', 'Feature_img4_00000', 'Feature_img5_00000', 'Feature_img6_00000', 'Feature_img7_00000', 'Feature_img8_00000', 'Feature_img9_00000'])
[[  2.40925264 112.49050903]
 [  2.65730381 117.12319183]
 [  3.74298596 168.68489075]
 ...
 [250.55123901 311.99728394]
 [251.71585083 277.08444214]
 [252.17602539 383.51010132]]
[[ 46.  13.   2. ...   0.   3.   0.]
 [  5.  37. 123. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [ 19.   0.   0. ...   0.   0.   0.]
 [154.  77.   7. ...   0.   0.   0.]
 [124.  22.   0. ...   0.   0.   0.]]
(484, 2)
(484, 128)
