In [1]:
import scipy
import numpy as np

In [2]:
data_voley = scipy.io.loadmat("volley/volley.mat")

In [3]:
print(data_voley.keys())

dict_keys(['__header__', '__version__', '__globals__', 'frame_00000', 'frame_00001', 'frame_00002', 'frame_00003', 'frame_00004', 'frame_00005', 'frame_00006', 'frame_00007', 'frame_00008', 'frame_00009', 'frame_00010', 'frame_00011', 'frame_00012', 'frame_00013', 'frame_00014', 'frame_00015', 'frame_00016', 'frame_00017', 'frame_00018', 'frame_00019', 'frame_00020', 'frame_00021', 'frame_00022', 'frame_00023', 'frame_00024', 'frame_00025', 'frame_00026', 'frame_00027', 'frame_00028', 'frame_00029', 'frame_00030', 'frame_00031', 'frame_00032', 'frame_00033', 'frame_00034', 'frame_00035', 'frame_00036', 'frame_00037', 'frame_00038', 'frame_00039', 'frame_00040', 'frame_00041', 'frame_00042', 'frame_00043', 'frame_00044', 'frame_00045', 'frame_00046', 'frame_00047', 'frame_00048', 'frame_00049', 'frame_00050', 'frame_00051', 'frame_00052', 'frame_00053', 'frame_00054', 'frame_00055', 'frame_00056', 'frame_00057', 'frame_00058', 'frame_00059', 'frame_00060', 'frame_00061', 'frame_00062', 

In [4]:
data_voley['frame_00496']['xyxy']


array([[array([[301.73517 , 202.90787 , 337.02356 , 296.6887  ],
               [454.81406 , 136.5535  , 484.44614 , 194.34575 ],
               [160.55112 , 176.44089 , 183.74687 , 246.21042 ],
               [276.2784  , 158.56137 , 294.3963  , 207.4308  ],
               [585.5046  , 233.89255 , 616.55695 , 289.12204 ],
               [  9.796109, 106.52081 ,  38.75892 , 168.61282 ],
               [479.06052 , 101.26871 , 499.15994 , 141.21161 ],
               [561.3597  , 172.5684  , 599.93854 , 226.80501 ],
               [338.83344 ,  88.37851 , 357.61166 , 146.92047 ],
               [205.89632 , 151.5648  , 229.17667 , 205.35614 ],
               [201.39137 , 200.27013 , 241.78227 , 272.32437 ]], dtype=float32)]],
      dtype=object)

In [5]:
data_voley['frame_00496']['id']

array([[array([[42., 58., 66., 82., 86., 88., 90., 92., 93., 91., 94.]],
              dtype=float32)                                            ]],
      dtype=object)

In [6]:
dir = data_voley.keys()
print(dir)

dict_keys(['__header__', '__version__', '__globals__', 'frame_00000', 'frame_00001', 'frame_00002', 'frame_00003', 'frame_00004', 'frame_00005', 'frame_00006', 'frame_00007', 'frame_00008', 'frame_00009', 'frame_00010', 'frame_00011', 'frame_00012', 'frame_00013', 'frame_00014', 'frame_00015', 'frame_00016', 'frame_00017', 'frame_00018', 'frame_00019', 'frame_00020', 'frame_00021', 'frame_00022', 'frame_00023', 'frame_00024', 'frame_00025', 'frame_00026', 'frame_00027', 'frame_00028', 'frame_00029', 'frame_00030', 'frame_00031', 'frame_00032', 'frame_00033', 'frame_00034', 'frame_00035', 'frame_00036', 'frame_00037', 'frame_00038', 'frame_00039', 'frame_00040', 'frame_00041', 'frame_00042', 'frame_00043', 'frame_00044', 'frame_00045', 'frame_00046', 'frame_00047', 'frame_00048', 'frame_00049', 'frame_00050', 'frame_00051', 'frame_00052', 'frame_00053', 'frame_00054', 'frame_00055', 'frame_00056', 'frame_00057', 'frame_00058', 'frame_00059', 'frame_00060', 'frame_00061', 'frame_00062', 

In [7]:
frame_vec = [key for key in dir if 'frame' in key]
print(frame_vec)

['frame_00000', 'frame_00001', 'frame_00002', 'frame_00003', 'frame_00004', 'frame_00005', 'frame_00006', 'frame_00007', 'frame_00008', 'frame_00009', 'frame_00010', 'frame_00011', 'frame_00012', 'frame_00013', 'frame_00014', 'frame_00015', 'frame_00016', 'frame_00017', 'frame_00018', 'frame_00019', 'frame_00020', 'frame_00021', 'frame_00022', 'frame_00023', 'frame_00024', 'frame_00025', 'frame_00026', 'frame_00027', 'frame_00028', 'frame_00029', 'frame_00030', 'frame_00031', 'frame_00032', 'frame_00033', 'frame_00034', 'frame_00035', 'frame_00036', 'frame_00037', 'frame_00038', 'frame_00039', 'frame_00040', 'frame_00041', 'frame_00042', 'frame_00043', 'frame_00044', 'frame_00045', 'frame_00046', 'frame_00047', 'frame_00048', 'frame_00049', 'frame_00050', 'frame_00051', 'frame_00052', 'frame_00053', 'frame_00054', 'frame_00055', 'frame_00056', 'frame_00057', 'frame_00058', 'frame_00059', 'frame_00060', 'frame_00061', 'frame_00062', 'frame_00063', 'frame_00064', 'frame_00065', 'frame_00

In [8]:
counter = -10

test_data_xyxy = data_voley[frame_vec[counter]]['xyxy']
print(test_data_xyxy[0][0])
print(test_data_xyxy[0][0].shape)

test_data_id = data_voley[frame_vec[counter]]['id']

print(test_data_id[0][0])
print(test_data_id[0][0].shape)

[[352.03473 206.6907  386.95502 299.30954]
 [189.47818 207.11926 215.80367 284.68018]
 [202.44066 147.15102 233.79086 211.44864]
 [285.69373 142.75615 313.22214 215.60463]
 [502.64255 183.19545 526.9245  265.55597]
 [425.12292 157.8058  444.29767 226.56754]
 [144.40172 171.17253 172.50603 241.71176]
 [475.17868 173.70665 496.0248  230.7696 ]
 [389.24463 183.55629 408.01248 214.57742]
 [444.5158  215.89565 476.41592 292.89658]
 [291.39172 219.08073 318.53748 302.35126]
 [312.75354 198.56621 341.02017 272.58203]]
(12, 4)
[[ 42.  66.  91.  96. 105. 106. 107. 108. 103. 109. 100. 110.]]
(1, 12)


In [9]:
test_data_xyxy[0][0][:, 0] - test_data_xyxy[0][0][:, 2]

array([-34.920288, -26.325485, -31.350204, -27.528412, -24.281952,
       -19.174744, -28.10431 , -20.84613 , -18.767853, -31.900116,
       -27.145752, -28.266632], dtype=float32)

In [11]:
data_2 = scipy.io.loadmat("volley/input/kp_0001.mat")

In [12]:
data_2.keys()

dict_keys(['__header__', '__version__', '__globals__', 'desc', 'kp'])

In [14]:
data_2['kp'].shape

(812, 2)

In [19]:
data_xyxy = data_voley['frame_00003']['xyxy'][0][0]
data_id = data_voley['frame_00003']['id'][0][0]


cm_x = (data_xyxy[:,0] + data_xyxy[:,2]) / 2
cm_y = (data_xyxy[:,1] + data_xyxy[:,3]) / 2

cm_points = np.column_stack((cm_x, cm_y))
cm_points_hom = np.column_stack((cm_points, np.ones((cm_points.shape[0], 1)))).T

In [23]:
print(cm_points)
print(cm_points_hom.shape)

[[ 76.225296 184.77203 ]
 [402.92154  127.83411 ]
 [368.7205   204.61005 ]
 [253.2613    94.00595 ]
 [339.2146    94.67466 ]
 [531.67755  231.16673 ]
 [563.6171    97.602425]
 [488.00616  176.99004 ]]
(3, 8)


In [ ]:
    
    # cm_x = (data_xyxy[:,0] + data_xyxy[:,2]) / 2
    # cm_y = (data_xyxy[:,1] + data_xyxy[:,3]) / 2
    
    # cm_points = np.column_stack((cm_x, cm_y))
    # cm_points_hom = np.column_stack((cm_points, np.ones((cm_points.shape[0], 1)))).T

In [24]:
k1 = 10
k2 = 100

k1_padded = str(k1).zfill(4)
k2_padded = str(k2).zfill(4)

print(k1_padded)  # Output: 0010
print(k2_padded)  # Output: 0100

0010
0100


In [32]:
###
data_yolo_test = scipy.io.loadmat("volley/input/yolo_0249.mat")

In [33]:
print(data_yolo_test.keys())

dict_keys(['__header__', '__version__', '__globals__', 'class', 'id', 'xyxy'])


In [35]:
print(data_yolo_test['xyxy'])
print(data_yolo_test['id'])

[[326.64     269.72626  363.7494   180.87267 ]
 [378.03906  199.57358  403.8358   141.19751 ]
 [470.57172  215.80435  497.21234  144.13885 ]
 [312.2186   122.51473  331.55655   71.41983 ]
 [270.6435   241.03583  303.1701   172.03674 ]
 [107.59027  237.78777  180.49913  196.86739 ]
 [200.6732   161.10031  236.42816  119.557816]
 [408.74332  189.64667  429.58356  128.17209 ]
 [ 19.94265  359.84622   60.533806 315.13284 ]]
[[42.]
 [52.]
 [56.]
 [61.]
 [62.]
 [64.]
 [65.]
 [58.]
 [67.]]
